routes/web.php
<?php

use App\Http\Livewire;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware(['auth:sanctum', 'verified'])
    ->group(function () {

    Route::get('dashboard', function () {
        return view('dashboard');
    })->name('dashboard');

    Route::name('animals.')
        ->prefix('animals/')
        ->group(function () {
            Route::get('/', Livewire\AnimalList::class)->name('list');
            Route::get('/new', Livewire\Animal::class)->name('new');
            Route::get('/{animal}', Livewire\Animal::class)->name('show');
        });

    Route::name('characteristics.')
        ->prefix('characteristics/')
        ->group(function () {
            Route::get('body-coverings/', Livewire\Characteristics\BodyCoveringList::class)->name('body-coverings.list');
            Route::get('body-coverings/new', Livewire\Characteristics\BodyCovering::class)->name('body-coverings.new');
            Route::get('body-coverings/{model}', Livewire\Characteristics\BodyCovering::class)->name('body-coverings.show');

            Route::get('body-structures/', Livewire\Characteristics\BodyStructureList::class)->name('body-structures.list');
            Route::get('body-structures/new', Livewire\Characteristics\BodyStructure::class)->name('body-structures.new');
            Route::get('body-structures/{model}', Livewire\Characteristics\BodyStructure::class)->name('body-structures.show');

            Route::get('breathing-methods/', Livewire\Characteristics\BreathingMethodList::class)->name('breathing-methods.list');
            Route::get('breathing-methods/new', Livewire\Characteristics\BreathingMethod::class)->name('breathing-methods.new');
            Route::get('breathing-methods/{model}', Livewire\Characteristics\BreathingMethod::class)->name('breathing-methods.show');

            Route::get('communication-methods/', Livewire\Characteristics\CommunicationMethodList::class)->name('communication-methods.list');
            Route::get('communication-methods/new', Livewire\Characteristics\CommunicationMethod::class)->name('communication-methods.new');
            Route::get('communication-methods/{model}', Livewire\Characteristics\CommunicationMethod::class)->name('communication-methods.show');

            Route::get('life-cycles/', Livewire\Characteristics\LifeCycleList::class)->name('life-cycles.list');
            Route::get('life-cycles/new', Livewire\Characteristics\LifeCycle::class)->name('life-cycles.new');
            Route::get('life-cycles/{model}', Livewire\Characteristics\LifeCycle::class)->name('life-cycles.show');

            Route::get('locomotion-methods/', Livewire\Characteristics\LocomotionMethodList::class)->name('locomotion-methods.list');
            Route::get('locomotion-methods/new', Livewire\Characteristics\LocomotionMethod::class)->name('locomotion-methods.new');
            Route::get('locomotion-methods/{model}', Livewire\Characteristics\LocomotionMethod::class)->name('locomotion-methods.show');

            Route::get('senses/', Livewire\Characteristics\SenseList::class)->name('senses.list');
            Route::get('senses/new', Livewire\Characteristics\Sense::class)->name('senses.new');
            Route::get('senses/{model}', Livewire\Characteristics\Sense::class)->name('senses.show');
        });
    });

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="p-8 bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <h2 class="text-2xl">Animals</h2>

                @php
                    $count = \App\Models\Animal::count();
                @endphp
                <p class="mt-4">Currently you have {{ __(':count :animal', ['count' => $count, 'animal' => Str::plural('animal', $count)]) }} in the database.</p>

                <p class="mt-4">
                    <x-button href="{{ route('animals.list') }}">
                        See Animals
                    </x-button>
                </p>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>